### ISSUE TITLE
Read and summarise literature

### ISSUE THREAD

**Issue by leowe** [hpi-swa-lab/BP2019RH1#10]
Please include links to summary (of useful / interesting visualisations)

Books:
- [ ] Truthful Art, Alberto Cairo; #12 
- [ ] Functional Art, Alberto Cairo; #13 
- [ ] Unflattening #26 
- [ ] A Small matter of programming #14 
- [ ] The Design of everyday things #28
- [ ] Information is beautiful #25 
- [ ] Things come apart #27
- [ ] How to Lie with Maps #29
- [ ] The Visual Display of Quantitative Data #30 
- [ ] Semiology of Graphics #31
- [ ] Dear Data #32
- [ ] Real World Research #33

Papers:
- [ ] AVF Reports #35 
- [ ] The Gamma: Programming tools for open data-driven storytelling #20 
- [ ] The Practices of Programming #21 
- [ ] Herding Cats: Observing Live Coding in the Wild #22 
- [ ] Incremental Relational Lenses #23 
- [ ] Exploratory and Live, Programming and Coding #24 
- [x] It Ain't Necessarily So #34

**Comment by leowe** [comment]
Also include papers sent by Patrick

**Comment by lpfennigschmidt** [comment]
included
